name: Run Stock Agent

on:
  schedule:
    - cron: '0 14 * * *'  # Runs every day at 14:00 UTC (~9am EST)
  workflow_dispatch:      # Allows manual triggering

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Agent
        run: python stock_agent.py
